# Generated by Django 3.0.7 on 2021-04-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achivment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivment_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mail', models.CharField(max_length=200)),
                ('Your_Message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_fdis', models.CharField(max_length=500)),
                ('look_pdis', models.CharField(max_length=500)),
                ('look_mintro', models.CharField(default='main_intro_ine', max_length=500)),
                ('look_wgol', models.CharField(default='main_intro_ine', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_name', models.CharField(max_length=500)),
                ('one_disone', models.CharField(max_length=500)),
                ('one_distwo', models.CharField(max_length=500)),
                ('one_date', models.CharField(max_length=500)),
                ('one_del', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='onet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_team', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='studing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studing_a', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_name', models.CharField(max_length=500)),
                ('three_disone', models.CharField(max_length=500)),
                ('three_distwo', models.CharField(max_length=500)),
                ('three_date', models.CharField(max_length=500)),
                ('three_del', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='threet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_team', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_name', models.CharField(max_length=500)),
                ('two_disone', models.CharField(max_length=500)),
                ('two_distwo', models.CharField(max_length=500)),
                ('two_date', models.CharField(max_length=500)),
                ('two_del', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='twot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_team', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=200)),
                ('view_intro', models.CharField(max_length=1000)),
            ],
        ),
    ]
